# Generated by Django 5.1.1 on 2024-10-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('game_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Active Game', models.BooleanField()),
                ('Game host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='Players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleplayerGame',
            fields=[
                ('game_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Active Game', models.BooleanField()),
                ('Game score', models.FloatField()),
                ('Game host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.singleplayergame')),
            ],
        ),
    ]
