# Generated by Django 5.1.1 on 2024-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayergame',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard')], default='Normal', max_length=6),
        ),
        migrations.AddField(
            model_name='singleplayergame',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard')], default='Normal', max_length=6),
        ),
    ]
