# Generated by Django 5.1.1 on 2024-10-04 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_active_game_multiplayergame_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayergame',
            name='Data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='singleplayergame',
            name='End',
            field=models.DateField(default=datetime.date(2024, 10, 4)),
        ),
        migrations.AddField(
            model_name='singleplayergame',
            name='Predictions',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='singleplayergame',
            name='Start',
            field=models.DateField(default=datetime.date(2024, 10, 4)),
        ),
        migrations.DeleteModel(
            name='GameChart',
        ),
    ]
