# Generated by Django 5.1.1 on 2024-10-04 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_singleplayergame_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayergame',
            name='End',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
