# Generated by Django 5.1.1 on 2024-10-07 20:48

import picklefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_singleplayergame_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplayergame',
            old_name='difficulty',
            new_name='Difficulty',
        ),
        migrations.RenameField(
            model_name='singleplayergame',
            old_name='difficulty',
            new_name='Difficulty',
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Data',
            field=picklefield.fields.PickledObjectField(default=b'', editable=False),
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Predictions',
            field=picklefield.fields.PickledObjectField(default=b'', editable=False),
        ),
    ]
