# Generated by Django 5.1.1 on 2024-10-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_difficulty_multiplayergame_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplayergame',
            old_name='Difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='singleplayergame',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
