# Generated by Django 5.1.1 on 2024-10-07 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_difficulty_multiplayergame_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayergame',
            name='End',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
