# Generated by Django 5.1.1 on 2024-10-07 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_singleplayergame_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayergame',
            name='End',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 7, 21, 3, 42, 247912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Start',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 7, 21, 3, 42, 247912, tzinfo=datetime.timezone.utc)),
        ),
    ]
