# Generated by Django 5.1.1 on 2024-10-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_singleplayergame_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayergame',
            name='Data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='singleplayergame',
            name='Predictions',
            field=models.JSONField(default=dict),
        ),
    ]
